// AUTO-GENERATED by scripts/prep-video.mjs — do not edit by hand.
export type Clip = {
  id: string; src: string; poster: string; blur: string
  w: number; h: number; ratio: number; duration: number
  orient: 'land' | 'port'
}
export const VIDEO: Record<string, Clip[]> = {
  "yum": [
    {
      "id": "V01",
      "src": "/work/yum/v01.mp4",
      "poster": "/work/yum/v01-poster.webp",
      "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAkABABoJbACdACmGvF6AAD+5pWsz+HzeMh1Klh4isNhAnHOkUOKpGq1siXm9MrdXMdrSD9dVyLmoF5QQqDDC+4cjRTH4vmCES4SZAAAAA==",
      "w": 1280,
      "h": 720,
      "ratio": 1.7778,
      "duration": 52,
      "orient": "land"
    }
  ],
  "la-tdc": [
    {
      "id": "V01",
      "src": "/work/la-tdc/v01.mp4",
      "poster": "/work/la-tdc/v01-poster.webp",
      "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkABABoJZACdAC4dd8yMsAA/qWOb0DnUK3mvAKJPJQyuVD9X16yiRWpvZijXfGH9AwPTnbuUMXKEkrvOoCtjMIAAA==",
      "w": 1280,
      "h": 720,
      "ratio": 1.7778,
      "duration": 114,
      "orient": "land"
    },
    {
      "id": "V02",
      "src": "/work/la-tdc/v02.mp4",
      "poster": "/work/la-tdc/v02-poster.webp",
      "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoQABwAPxF2slEsJySisAgBgCIJbACdMoR4GCm93OPmfLDU88QAAP5u5CwrjOuNoByHeckxn2KpnyLhjKoonYvxEkwZB6CUPi4KoPF+Gedw6PKoQhUeRpv5YR+/5PS9kRv64ZJNqcCZp5iQulG7CYTD1mSR2OojcAA=",
      "w": 720,
      "h": 1280,
      "ratio": 0.5625,
      "duration": 33,
      "orient": "port"
    }
  ],
  "deporte": [
    {
      "id": "V01",
      "src": "/work/deporte/v01.mp4",
      "poster": "/work/deporte/v01-poster.webp",
      "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAkABABoJZAAAqBo6nxlDQAA3Lgy/DMWRPUKfJiNBLlxK8I2swnNEbux3LMdhzmji+QPPIxfIno/+1IDjjgA",
      "w": 1280,
      "h": 720,
      "ratio": 1.7778,
      "duration": 24,
      "orient": "land"
    }
  ],
  "kevin-florez": [
    {
      "id": "V01",
      "src": "/work/kevin-florez/v01.mp4",
      "poster": "/work/kevin-florez/v01-poster.webp",
      "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAAkABABoJaACdAYuRqdSnWxxgAD+sgm3Xd6KxOGBG+y13yba+lf6tAE57/7DUySLayNPxsvBSS5mX2QHUZRpEtLhind6XLSKuAAA",
      "w": 1280,
      "h": 720,
      "ratio": 1.7778,
      "duration": 96,
      "orient": "land"
    }
  ]
}
