import sharp from 'sharp'
import { readdir, mkdir, writeFile, rm } from 'node:fs/promises'
import path from 'node:path'

const SRC = '/private/tmp/claude-501/-Users-rulocode-dev-side-kuadra/813f2a77-66ad-4760-a7b0-7d52d1524d56/scratchpad/bh/masters'
const PUB = path.resolve('./public/work')
const DATA = path.resolve('./lib/media.ts')

const PROJECTS = [
  { slug: 'yum',           code: 'KDR—001' },
  { slug: 'la-tdc',        code: 'KDR—002' },
  { slug: 'deporte',       code: 'KDR—003' },
  { slug: 'fxa-moda',      code: 'KDR—004' },
  { slug: 'kevin-florez',  code: 'KDR—005' },
]

await rm(PUB, { recursive: true, force: true })
await mkdir(PUB, { recursive: true })

const out = {}
for (const p of PROJECTS) {
  const dir = path.join(SRC, p.slug)
  const files = (await readdir(dir)).filter(f => /\.(jpe?g|png|webp|gif)$/i.test(f)).sort()
  await mkdir(path.join(PUB, p.slug), { recursive: true })
  const items = []
  for (const [i, f] of files.entries()) {
    const id = String(i + 1).padStart(2, '0')
    const input = path.join(dir, f)
    const img = sharp(input, { animated: false })
    const md = await img.metadata()
    const long = Math.max(md.width, md.height)

    const fullName = `${id}.webp`
    const thumbName = `${id}-t.webp`
    const fullScale = Math.min(1, 1800 / long)
    const thumbScale = Math.min(1, 900 / long)

    await sharp(input).resize({ width: Math.round(md.width * fullScale), withoutEnlargement: true })
      .webp({ quality: 82, effort: 5 }).toFile(path.join(PUB, p.slug, fullName))
    await sharp(input).resize({ width: Math.round(md.width * thumbScale), withoutEnlargement: true })
      .webp({ quality: 72, effort: 5 }).toFile(path.join(PUB, p.slug, thumbName))

    // tiny blur placeholder
    const tiny = await sharp(input).resize({ width: 16 }).webp({ quality: 30 }).toBuffer()
    const blur = `data:image/webp;base64,${tiny.toString('base64')}`
    // dominant colour
    const { dominant } = await sharp(input).stats()
    const hex = '#' + [dominant.r, dominant.g, dominant.b].map(v => v.toString(16).padStart(2, '0')).join('')

    items.push({
      id, w: Math.round(md.width * fullScale), h: Math.round(md.height * fullScale),
      ratio: +(md.width / md.height).toFixed(4),
      src: `/work/${p.slug}/${fullName}`, thumb: `/work/${p.slug}/${thumbName}`,
      blur, hex,
      orient: md.width / md.height > 1.15 ? 'land' : md.width / md.height < 0.87 ? 'port' : 'sq',
    })
  }
  out[p.slug] = items
  const counts = items.reduce((a, i) => ({ ...a, [i.orient]: (a[i.orient] || 0) + 1 }), {})
  console.log(`${p.slug}: ${items.length} imgs`, counts)
}

const ts = `// AUTO-GENERATED by scripts/prep-media.mjs — do not edit by hand.
export type Shot = {
  id: string; w: number; h: number; ratio: number
  src: string; thumb: string; blur: string; hex: string
  orient: 'land' | 'port' | 'sq'
}
export const MEDIA: Record<string, Shot[]> = ${JSON.stringify(out, null, 2)} as const
`
await mkdir(path.dirname(DATA), { recursive: true })
await writeFile(DATA, ts)
console.log('\n✔ lib/media.ts written')
