/**
 * Transcodes the Behance (Adobe CCV) clips kept in ../media-masters/<slug>/video
 * into web-ready H.264 MP4s under public/work/<slug>/ and generates lib/video.ts.
 *
 *   node scripts/prep-video.mjs
 *
 * Masters are named vNN-<ccvId>.mp4 with a vNN-<ccvId>-poster.jpg next to them.
 * Output caps the long edge at 1280px, CRF 27, faststart — the site is
 * mobile-first and the player only loads on tap, so bytes matter more than 1080p.
 */
import sharp from 'sharp'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { readdir, mkdir, writeFile, stat } from 'node:fs/promises'
import path from 'node:path'

const run = promisify(execFile)
const SRC = path.resolve('../media-masters')
const PUB = path.resolve('./public/work')
const DATA = path.resolve('./lib/video.ts')
const SLUGS = ['yum', 'la-tdc', 'deporte', 'fxa-moda', 'kevin-florez']

const probe = async (file) => {
  const { stdout } = await run('ffprobe', [
    '-v', 'error', '-select_streams', 'v:0',
    '-show_entries', 'stream=width,height:format=duration',
    '-of', 'json', file,
  ])
  const j = JSON.parse(stdout)
  return { w: j.streams[0].width, h: j.streams[0].height, duration: +j.format.duration }
}

const out = {}
for (const slug of SLUGS) {
  const dir = path.join(SRC, slug, 'video')
  let files = []
  try { files = (await readdir(dir)).filter((f) => /^v\d+-.+\.mp4$/i.test(f)).sort() } catch { /* no clips */ }
  const items = []
  for (const f of files) {
    const id = f.match(/^v(\d+)/)[1]
    const input = path.join(dir, f)
    const poster = path.join(dir, f.replace(/\.mp4$/i, '-poster.jpg'))
    const md = await probe(input)
    const port = md.h > md.w
    const scale = port ? 'scale=-2:min(1280\\,ih)' : 'scale=min(1280\\,iw):-2'
    const outDir = path.join(PUB, slug)
    await mkdir(outDir, { recursive: true })
    const mp4 = path.join(outDir, `v${id}.mp4`)
    await run('ffmpeg', [
      '-y', '-i', input,
      '-vf', scale,
      '-c:v', 'libx264', '-preset', 'slow', '-crf', '27', '-profile:v', 'high', '-level', '4.0',
      '-pix_fmt', 'yuv420p', '-movflags', '+faststart',
      '-c:a', 'aac', '-b:a', '96k', '-ac', '2',
      mp4,
    ])
    const o = await probe(mp4)
    const bytes = (await stat(mp4)).size

    const posterOut = path.join(outDir, `v${id}-poster.webp`)
    const pimg = sharp(poster)
    await pimg.clone().resize({ width: port ? 900 : 1600, withoutEnlargement: true })
      .webp({ quality: 78, effort: 5 }).toFile(posterOut)
    const tiny = await pimg.clone().resize({ width: 16 }).webp({ quality: 30 }).toBuffer()

    items.push({
      id: `V${id}`,
      src: `/work/${slug}/v${id}.mp4`,
      poster: `/work/${slug}/v${id}-poster.webp`,
      blur: `data:image/webp;base64,${tiny.toString('base64')}`,
      w: o.w, h: o.h, ratio: +(o.w / o.h).toFixed(4),
      duration: Math.round(o.duration),
      orient: port ? 'port' : 'land',
    })
    console.log(`${slug} v${id}: ${o.w}x${o.h} ${Math.round(o.duration)}s ${(bytes / 1e6).toFixed(1)}MB`)
  }
  if (items.length) out[slug] = items
}

const ts = `// AUTO-GENERATED by scripts/prep-video.mjs — do not edit by hand.
export type Clip = {
  id: string; src: string; poster: string; blur: string
  w: number; h: number; ratio: number; duration: number
  orient: 'land' | 'port'
}
export const VIDEO: Record<string, Clip[]> = ${JSON.stringify(out, null, 2)}
`
await writeFile(DATA, ts)
console.log('\n✔ lib/video.ts written')
